-- vim.cmd('colorscheme gruvbox-baby')
-- vim.g.gruvbox_baby_function_style = "italic"
-- vim.g.gruvbox_baby_keyword_style = "bold"
-- vim.g.gruvbox_baby_telescope_theme = 1
-- vim.g.gruvbox_baby_transparent_mode = 0
-- vim.g.background_color = "soft"

-- -- Default options:
-- require("gruvbox").setup({
--     terminal_colors = true, -- add neovim terminal colors
--     undercurl = true,
--     underline = true,
--     bold = true,
--     italic = {
--         strings = true,
--         emphasis = true,
--         comments = true,
--         operators = false,
--         folds = true,
--     },
--     strikethrough = true,
--     invert_selection = false,
--     invert_signs = false,
--     invert_tabline = false,
--     invert_intend_guides = false,
--     contrast = "hard",
--     palette_overrides = {},
--     dim_inactive = false,
--     transparent_mode = true,
--     inverse = true, -- Keep inverse enabled
--     overrides = {
--         SignColumn = {bg = "none"},
--         Search = { fg = "#7c6f64", bg = "none"},
--         IncSearch = { fg = "#7c6f64", bg = "none"},
--     },
-- })
-- vim.cmd("colorscheme gruvbox")
